"""Generates llms.txt and llms-full.txt files following the llmstxt.org specification."""

from collections.abc import Mapping
from pathlib import Path
from typing import Any


def generate_llms_files(
    manifest: Mapping[str, Any],
    output_dir: Path,
    site_title: str,
) -> tuple[Path, Path]:
    """Generate llms.txt and llms-full.txt files in output_dir."""
    files = manifest.get("files", [])

    # --- 1. Generate llms.txt -----------------------------------------------
    llms_lines = [
        f"# {site_title}",
        "",
        "> Documentation site index and sitemap for LLMs and AI agents.",
        "",
        "## Documentation Pages",
    ]

    for f in files:
        title = f.get("title") or f.get("relpath")
        src = f.get("md_src") or f.get("src", "")
        headings = f.get("headings", [])
        if headings:
            heading_names = [h.get("text", "") for h in headings[:4] if h.get("text")]
            desc = "Sections: " + ", ".join(heading_names)
        else:
            text = f.get("text", "").strip()
            desc = text[:120].replace("\n", " ") + "…" if len(text) > 120 else text

        llms_lines.append(f"- [{title}]({src}): {desc}")

    llms_lines.extend(
        [
            "",
            "## Optional",
            "- [Full Documentation Corpus](llms-full.txt): Complete plain text and markdown documentation in a single file.",
            "",
        ]
    )

    llms_txt_path = output_dir / "llms.txt"
    llms_txt_path.write_text("\n".join(llms_lines), encoding="utf-8")

    # --- 2. Generate llms-full.txt ------------------------------------------
    full_lines = [
        f"# {site_title} — Complete Documentation",
        "",
        "> Consolidated documentation corpus generated by docs-site.",
        "",
    ]

    for f in files:
        relpath = f.get("relpath", "")
        title = f.get("title", "")
        ftype = f.get("type", "")
        doc_src = f.get("md_src") or f.get("raw_src")

        content = ""
        if doc_src:
            doc_path = output_dir / doc_src
            if doc_path.is_file():
                content = doc_path.read_text(encoding="utf-8", errors="replace")

        if not content:
            content = f.get("text", "")

        full_lines.extend(
            [
                "---",
                f"## File: {relpath}",
                f"Title: {title}",
                f"Type: {ftype}",
                "",
                content.strip(),
                "",
            ]
        )

    llms_full_path = output_dir / "llms-full.txt"
    llms_full_path.write_text("\n".join(full_lines), encoding="utf-8")

    return llms_txt_path, llms_full_path
